# This is a basic workflow to help you get started with Actions

name: CI of op-app-skeleton-2022-nep

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on

    # https://github.com/marketplace/actions/setup-php-environment
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: [ '7.4' ] # [ '5.4', '5.5', '5.6', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1' ]
    name: PHP ${{ matrix.php }} sample

    # Steps represent a sequence of tasks that will be executed as part of the job
    # Do ”Steps” run in parallel?
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # https://tech.fusic.co.jp/posts/2021-11-17-github-actions-cache/
      - uses: actions/cache@v2
        with:
          path: ~/
          key: php-${{ hashFiles('.gitignore') }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      # https://github.com/marketplace/actions/setup-php-action
      # https://github.com/marketplace/actions/setup-php-environment
      - name: Setup PHP
        uses: nanasess/setup-php@v3
        with:
          php-version: ${{ matrix.php }}

      - run: php app.php
      - name: Change github account name
        if: ${{ secrets.ACCOUNT }}
        run: sh asset/git/submodule/github.sh ${{ secrets.ACCOUNT }}
      - run: sh asset/git/submodule/init.sh   2022
      - run: php ci.php display=1
